
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Button btnIniciar;

	private global::Gtk.Button btnSalir;

	private global::Gtk.Entry txtClave;

	private global::Gtk.Entry txtUsuario;

	private global::Gtk.Label label2;

	private global::Gtk.Label label1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnIniciar = new global::Gtk.Button();
		this.btnIniciar.CanFocus = true;
		this.btnIniciar.Name = "btnIniciar";
		this.btnIniciar.UseUnderline = true;
		this.btnIniciar.Label = global::Mono.Unix.Catalog.GetString("Iniciar sesion");
		this.fixed1.Add(this.btnIniciar);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnIniciar]));
		w1.X = 229;
		w1.Y = 188;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnSalir = new global::Gtk.Button();
		this.btnSalir.CanFocus = true;
		this.btnSalir.Name = "btnSalir";
		this.btnSalir.UseUnderline = true;
		this.btnSalir.Label = global::Mono.Unix.Catalog.GetString("Salir del programa");
		this.fixed1.Add(this.btnSalir);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnSalir]));
		w2.X = 42;
		w2.Y = 188;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtClave = new global::Gtk.Entry();
		this.txtClave.CanFocus = true;
		this.txtClave.Name = "txtClave";
		this.txtClave.IsEditable = true;
		this.txtClave.Visibility = false;
		this.txtClave.InvisibleChar = '•';
		this.fixed1.Add(this.txtClave);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtClave]));
		w3.X = 138;
		w3.Y = 86;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtUsuario = new global::Gtk.Entry();
		this.txtUsuario.CanFocus = true;
		this.txtUsuario.Name = "txtUsuario";
		this.txtUsuario.IsEditable = true;
		this.txtUsuario.InvisibleChar = '•';
		this.fixed1.Add(this.txtUsuario);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtUsuario]));
		w4.X = 137;
		w4.Y = 40;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Clave");
		this.fixed1.Add(this.label2);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
		w5.X = 79;
		w5.Y = 92;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Usuario");
		this.fixed1.Add(this.label1);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
		w6.X = 64;
		w6.Y = 46;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnIniciar.Clicked += new global::System.EventHandler(this.OnBtnIniciarClicked);
		this.btnSalir.Clicked += new global::System.EventHandler(this.OnBtnSalirClicked);
	}
}
