
// This file has been generated by the GUI designer. Do not modify.
namespace Sistema.Datos
{
	public partial class DT_tbl_Cargo
	{
		public virtual void Build()
		{
			// Action group Sistema.Datos.DT_tbl_Cargo
		}
	}
}
