
// This file has been generated by the GUI designer. Do not modify.
namespace Sistema
{
	public partial class MarcarAsistencia
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label label1;

		private global::Gtk.Label label2;

		private global::Gtk.Entry TxtCedula;

		private global::Gtk.Button BtnEntrada;

		private global::Gtk.Button BtnSalida;

		private global::Gtk.Calendar calendar1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView tvListaAsistencia;

		private global::Gtk.Label lblHora;

		private global::Gtk.Label label3;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Sistema.MarcarAsistencia
			this.Name = "Sistema.MarcarAsistencia";
			this.Title = global::Mono.Unix.Catalog.GetString("MarcarAsistencia");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Sistema.MarcarAsistencia.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Registro de asistencia");
			this.fixed1.Add(this.label1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
			w1.X = 114;
			w1.Y = 25;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Cedula del empleado");
			this.fixed1.Add(this.label2);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
			w2.X = 119;
			w2.Y = 70;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.TxtCedula = new global::Gtk.Entry();
			this.TxtCedula.CanFocus = true;
			this.TxtCedula.Name = "TxtCedula";
			this.TxtCedula.IsEditable = true;
			this.TxtCedula.InvisibleChar = '•';
			this.fixed1.Add(this.TxtCedula);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.TxtCedula]));
			w3.X = 107;
			w3.Y = 94;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.BtnEntrada = new global::Gtk.Button();
			this.BtnEntrada.CanFocus = true;
			this.BtnEntrada.Name = "BtnEntrada";
			this.BtnEntrada.UseUnderline = true;
			this.BtnEntrada.Label = global::Mono.Unix.Catalog.GetString("Entrada");
			this.fixed1.Add(this.BtnEntrada);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.BtnEntrada]));
			w4.X = 108;
			w4.Y = 145;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.BtnSalida = new global::Gtk.Button();
			this.BtnSalida.CanFocus = true;
			this.BtnSalida.Name = "BtnSalida";
			this.BtnSalida.UseUnderline = true;
			this.BtnSalida.Label = global::Mono.Unix.Catalog.GetString("Salida");
			this.fixed1.Add(this.BtnSalida);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.BtnSalida]));
			w5.X = 223;
			w5.Y = 144;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.calendar1 = new global::Gtk.Calendar();
			this.calendar1.CanFocus = true;
			this.calendar1.Name = "calendar1";
			this.calendar1.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.fixed1.Add(this.calendar1);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.calendar1]));
			w6.X = 79;
			w6.Y = 210;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvListaAsistencia = new global::Gtk.TreeView();
			this.tvListaAsistencia.WidthRequest = 400;
			this.tvListaAsistencia.HeightRequest = 300;
			this.tvListaAsistencia.CanFocus = true;
			this.tvListaAsistencia.Name = "tvListaAsistencia";
			this.GtkScrolledWindow.Add(this.tvListaAsistencia);
			this.fixed1.Add(this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
			w8.X = 381;
			w8.Y = 34;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblHora = new global::Gtk.Label();
			this.lblHora.Name = "lblHora";
			this.lblHora.LabelProp = global::Mono.Unix.Catalog.GetString("hh:mm:ss");
			this.fixed1.Add(this.lblHora);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblHora]));
			w9.X = 582;
			w9.Y = 366;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Hora:");
			this.fixed1.Add(this.label3);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
			w10.X = 504;
			w10.Y = 365;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 839;
			this.DefaultHeight = 442;
			this.Show();
			this.BtnEntrada.Clicked += new global::System.EventHandler(this.OnBtnEntradaClicked);
			this.BtnSalida.Clicked += new global::System.EventHandler(this.OnBtnSalidaClicked);
		}
	}
}
