
// This file has been generated by the GUI designer. Do not modify.
namespace Sistema
{
	public partial class AsignarEmpleado
	{
		private global::Gtk.Fixed fixed2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView tvEmpleadoCargo;

		private global::Gtk.Label label3;

		private global::Gtk.Button btnRegresar;

		private global::Gtk.Button bntGuardar;

		private global::Gtk.Button btnEliminar;

		private global::Gtk.Label label8;

		private global::Gtk.ComboBox cbCargo;

		private global::Gtk.Entry txtIdEmpleado;

		private global::Gtk.Entry txtIdCargo;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Sistema.AsignarEmpleado
			this.Name = "Sistema.AsignarEmpleado";
			this.Title = global::Mono.Unix.Catalog.GetString("AsignarEmpleado");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Sistema.AsignarEmpleado.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvEmpleadoCargo = new global::Gtk.TreeView();
			this.tvEmpleadoCargo.WidthRequest = 400;
			this.tvEmpleadoCargo.HeightRequest = 200;
			this.tvEmpleadoCargo.CanFocus = true;
			this.tvEmpleadoCargo.Name = "tvEmpleadoCargo";
			this.GtkScrolledWindow.Add(this.tvEmpleadoCargo);
			this.fixed2.Add(this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.GtkScrolledWindow]));
			w2.X = 9;
			w2.Y = 305;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Id Empleado");
			this.fixed2.Add(this.label3);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label3]));
			w3.X = 22;
			w3.Y = 58;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.btnRegresar = new global::Gtk.Button();
			this.btnRegresar.CanFocus = true;
			this.btnRegresar.Name = "btnRegresar";
			this.btnRegresar.UseUnderline = true;
			this.btnRegresar.Label = global::Mono.Unix.Catalog.GetString("Regresar");
			this.fixed2.Add(this.btnRegresar);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.btnRegresar]));
			w4.X = 18;
			w4.Y = 533;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.bntGuardar = new global::Gtk.Button();
			this.bntGuardar.CanFocus = true;
			this.bntGuardar.Name = "bntGuardar";
			this.bntGuardar.UseUnderline = true;
			this.bntGuardar.Label = global::Mono.Unix.Catalog.GetString("Guardar");
			this.fixed2.Add(this.bntGuardar);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.bntGuardar]));
			w5.X = 15;
			w5.Y = 250;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.btnEliminar = new global::Gtk.Button();
			this.btnEliminar.CanFocus = true;
			this.btnEliminar.Name = "btnEliminar";
			this.btnEliminar.UseUnderline = true;
			this.btnEliminar.Label = global::Mono.Unix.Catalog.GetString("Eliminar");
			this.fixed2.Add(this.btnEliminar);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.btnEliminar]));
			w6.X = 110;
			w6.Y = 251;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Cargo");
			this.fixed2.Add(this.label8);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label8]));
			w7.X = 38;
			w7.Y = 102;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.cbCargo = global::Gtk.ComboBox.NewText();
			this.cbCargo.Name = "cbCargo";
			this.fixed2.Add(this.cbCargo);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.cbCargo]));
			w8.X = 122;
			w8.Y = 91;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.txtIdEmpleado = new global::Gtk.Entry();
			this.txtIdEmpleado.CanFocus = true;
			this.txtIdEmpleado.Name = "txtIdEmpleado";
			this.txtIdEmpleado.IsEditable = true;
			this.txtIdEmpleado.InvisibleChar = '•';
			this.fixed2.Add(this.txtIdEmpleado);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.txtIdEmpleado]));
			w9.X = 126;
			w9.Y = 42;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.txtIdCargo = new global::Gtk.Entry();
			this.txtIdCargo.WidthRequest = 18;
			this.txtIdCargo.HeightRequest = 27;
			this.txtIdCargo.Sensitive = false;
			this.txtIdCargo.CanFocus = true;
			this.txtIdCargo.Name = "txtIdCargo";
			this.txtIdCargo.IsEditable = true;
			this.txtIdCargo.InvisibleChar = '•';
			this.fixed2.Add(this.txtIdCargo);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.txtIdCargo]));
			w10.X = 97;
			w10.Y = 96;
			this.Add(this.fixed2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 486;
			this.DefaultHeight = 583;
			this.Show();
			this.tvEmpleadoCargo.CursorChanged += new global::System.EventHandler(this.OnTvEmpleadoCargoCursorChanged);
			this.btnRegresar.Clicked += new global::System.EventHandler(this.OnBtnRegresarClicked);
			this.bntGuardar.Clicked += new global::System.EventHandler(this.OnBntGuardarClicked);
			this.btnEliminar.Clicked += new global::System.EventHandler(this.OnBtnEliminarClicked);
		}
	}
}
