
// This file has been generated by the GUI designer. Do not modify.
namespace Sistema
{
	public partial class Menu
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action EmpleadosAction;

		private global::Gtk.Action CargosYDepartamentosAction;

		private global::Gtk.Action ListarEmpleadosAction;

		private global::Gtk.Action AdministrarCargosAction;

		private global::Gtk.Action EmpleadosAction1;

		private global::Gtk.Action ListarEmpleadosAction1;

		private global::Gtk.Action CargosYDepartamentosAction1;

		private global::Gtk.Action AsignarCargosAction;

		private global::Gtk.Action AdministrarDepartamentosAction;

		private global::Gtk.Action AdministrarCargosAction1;

		private global::Gtk.Action Action;

		private global::Gtk.Action XDAction;

		private global::Gtk.Action AdministracionDeCargosAction;

		private global::Gtk.VBox vbox1;

		private global::Gtk.MenuBar menubar1;

		private global::Gtk.VBox vbox5;

		private global::Gtk.Label label16;

		private global::Gtk.HBox hbox2;

		private global::Gtk.VBox vbox4;

		private global::Gtk.Button btnCerrar;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Sistema.Menu
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.EmpleadosAction = new global::Gtk.Action("EmpleadosAction", global::Mono.Unix.Catalog.GetString("Empleados"), null, null);
			this.EmpleadosAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Empleados");
			w1.Add(this.EmpleadosAction, null);
			this.CargosYDepartamentosAction = new global::Gtk.Action("CargosYDepartamentosAction", global::Mono.Unix.Catalog.GetString("Cargos y departamentos"), null, null);
			this.CargosYDepartamentosAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Cargos y departamentos");
			w1.Add(this.CargosYDepartamentosAction, null);
			this.ListarEmpleadosAction = new global::Gtk.Action("ListarEmpleadosAction", global::Mono.Unix.Catalog.GetString("Listar empleados"), null, null);
			this.ListarEmpleadosAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Listar empleados");
			w1.Add(this.ListarEmpleadosAction, null);
			this.AdministrarCargosAction = new global::Gtk.Action("AdministrarCargosAction", global::Mono.Unix.Catalog.GetString("Administrar cargos"), null, null);
			this.AdministrarCargosAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Administrar cargos");
			w1.Add(this.AdministrarCargosAction, null);
			this.EmpleadosAction1 = new global::Gtk.Action("EmpleadosAction1", global::Mono.Unix.Catalog.GetString("Empleados"), null, null);
			this.EmpleadosAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Empleados");
			w1.Add(this.EmpleadosAction1, null);
			this.ListarEmpleadosAction1 = new global::Gtk.Action("ListarEmpleadosAction1", global::Mono.Unix.Catalog.GetString("Listar empleados"), null, null);
			this.ListarEmpleadosAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Listar empleados");
			w1.Add(this.ListarEmpleadosAction1, null);
			this.CargosYDepartamentosAction1 = new global::Gtk.Action("CargosYDepartamentosAction1", global::Mono.Unix.Catalog.GetString("Cargos y departamentos"), null, null);
			this.CargosYDepartamentosAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Cargos y departamentos");
			w1.Add(this.CargosYDepartamentosAction1, null);
			this.AsignarCargosAction = new global::Gtk.Action("AsignarCargosAction", global::Mono.Unix.Catalog.GetString("Asignar cargos"), null, null);
			this.AsignarCargosAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Administrar cargos");
			w1.Add(this.AsignarCargosAction, null);
			this.AdministrarDepartamentosAction = new global::Gtk.Action("AdministrarDepartamentosAction", global::Mono.Unix.Catalog.GetString("Administrar departamentos"), null, null);
			this.AdministrarDepartamentosAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Administrar departamentos");
			w1.Add(this.AdministrarDepartamentosAction, null);
			this.AdministrarCargosAction1 = new global::Gtk.Action("AdministrarCargosAction1", global::Mono.Unix.Catalog.GetString("Administrar cargos"), null, null);
			this.AdministrarCargosAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Administrar cargos");
			w1.Add(this.AdministrarCargosAction1, null);
			this.Action = new global::Gtk.Action("Action", global::Mono.Unix.Catalog.GetString("."), null, null);
			this.Action.ShortLabel = global::Mono.Unix.Catalog.GetString(".");
			w1.Add(this.Action, null);
			this.XDAction = new global::Gtk.Action("XDAction", global::Mono.Unix.Catalog.GetString("XD"), null, null);
			this.XDAction.ShortLabel = global::Mono.Unix.Catalog.GetString("XD");
			w1.Add(this.XDAction, null);
			this.AdministracionDeCargosAction = new global::Gtk.Action("AdministracionDeCargosAction", global::Mono.Unix.Catalog.GetString("Administracion de cargos"), null, null);
			this.AdministracionDeCargosAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Administracion de cargos");
			w1.Add(this.AdministracionDeCargosAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "Sistema.Menu";
			this.Title = global::Mono.Unix.Catalog.GetString("Menu");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Sistema.Menu.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString(@"<ui><menubar name='menubar1'><menu name='EmpleadosAction1' action='EmpleadosAction1'><menuitem name='ListarEmpleadosAction1' action='ListarEmpleadosAction1'/></menu><menu name='CargosYDepartamentosAction1' action='CargosYDepartamentosAction1'><menuitem name='AsignarCargosAction' action='AsignarCargosAction'/><menuitem name='AdministrarDepartamentosAction' action='AdministrarDepartamentosAction'/><menuitem name='AdministracionDeCargosAction' action='AdministracionDeCargosAction'/></menu></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox1.Add(this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.label16 = new global::Gtk.Label();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("Bienvenido administrador");
			this.vbox5.Add(this.label16);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.label16]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox1.Add(this.vbox5);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox5]));
			w4.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.btnCerrar = new global::Gtk.Button();
			this.btnCerrar.CanFocus = true;
			this.btnCerrar.Name = "btnCerrar";
			this.btnCerrar.UseUnderline = true;
			this.btnCerrar.Label = global::Mono.Unix.Catalog.GetString("Cerrar sesion");
			this.vbox4.Add(this.btnCerrar);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.btnCerrar]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.hbox2.Add(this.vbox4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox4]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w7.Position = 2;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 486;
			this.DefaultHeight = 300;
			this.Show();
			
			this.ListarEmpleadosAction1.Activated += new global::System.EventHandler(this.OnListarEmpleadosAction1Activated);
			this.AsignarCargosAction.Activated += new global::System.EventHandler(this.OnAsignarCargosActionActivated);
			this.AdministrarDepartamentosAction.Activated += new global::System.EventHandler(this.OnAdministrarDepartamentosActionActivated);
			
			this.AdministracionDeCargosAction.Activated += new global::System.EventHandler(this.OnAdministracionDeCargosActionActivated);
			this.btnCerrar.Clicked += new global::System.EventHandler(this.OnBtnCerrarClicked);
		}
	}
}
