
// This file has been generated by the GUI designer. Do not modify.
namespace Sistema
{
	public partial class LIstarEmpleado
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label label1;

		private global::Gtk.Entry txtNombre;

		private global::Gtk.Entry txtApellido;

		private global::Gtk.Label label2;

		private global::Gtk.Label label3;

		private global::Gtk.Entry txtTelefono;

		private global::Gtk.Entry txtCiudad;

		private global::Gtk.Label label4;

		private global::Gtk.Label label5;

		private global::Gtk.Entry txtCedula;

		private global::Gtk.Label label6;

		private global::Gtk.Entry txtPersonal;

		private global::Gtk.Label label7;

		private global::Gtk.Entry txtLaboral;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView tvListaEmpleado;

		private global::Gtk.Button btnGuardar;

		private global::Gtk.Button btnEliminar;

		private global::Gtk.Button btnModificar;

		private global::Gtk.Button btnRegresar;

		private global::Gtk.Entry txtDireccion;

		private global::Gtk.Entry txtId;

		private global::Gtk.Label label8;

		private global::Gtk.Label label9;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Sistema.LIstarEmpleado
			this.Name = "Sistema.LIstarEmpleado";
			this.Title = global::Mono.Unix.Catalog.GetString("LIstarEmpleado");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Sistema.LIstarEmpleado.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre");
			this.fixed1.Add(this.label1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
			w1.X = 21;
			w1.Y = 37;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtNombre = new global::Gtk.Entry();
			this.txtNombre.CanFocus = true;
			this.txtNombre.Name = "txtNombre";
			this.txtNombre.IsEditable = true;
			this.txtNombre.InvisibleChar = '•';
			this.fixed1.Add(this.txtNombre);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtNombre]));
			w2.X = 88;
			w2.Y = 29;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtApellido = new global::Gtk.Entry();
			this.txtApellido.CanFocus = true;
			this.txtApellido.Name = "txtApellido";
			this.txtApellido.IsEditable = true;
			this.txtApellido.InvisibleChar = '•';
			this.fixed1.Add(this.txtApellido);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtApellido]));
			w3.X = 89;
			w3.Y = 78;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Apellido");
			this.fixed1.Add(this.label2);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
			w4.X = 22;
			w4.Y = 84;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Telefono");
			this.fixed1.Add(this.label3);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
			w5.X = 22;
			w5.Y = 132;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtTelefono = new global::Gtk.Entry();
			this.txtTelefono.CanFocus = true;
			this.txtTelefono.Name = "txtTelefono";
			this.txtTelefono.IsEditable = true;
			this.txtTelefono.InvisibleChar = '•';
			this.fixed1.Add(this.txtTelefono);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtTelefono]));
			w6.X = 89;
			w6.Y = 124;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtCiudad = new global::Gtk.Entry();
			this.txtCiudad.CanFocus = true;
			this.txtCiudad.Name = "txtCiudad";
			this.txtCiudad.IsEditable = true;
			this.txtCiudad.InvisibleChar = '•';
			this.fixed1.Add(this.txtCiudad);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtCiudad]));
			w7.X = 91;
			w7.Y = 175;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Ciudad");
			this.fixed1.Add(this.label4);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label4]));
			w8.X = 31;
			w8.Y = 182;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Cedula");
			this.fixed1.Add(this.label5);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label5]));
			w9.X = 32;
			w9.Y = 230;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtCedula = new global::Gtk.Entry();
			this.txtCedula.CanFocus = true;
			this.txtCedula.Name = "txtCedula";
			this.txtCedula.IsEditable = true;
			this.txtCedula.InvisibleChar = '•';
			this.fixed1.Add(this.txtCedula);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtCedula]));
			w10.X = 91;
			w10.Y = 222;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Correo personal");
			this.fixed1.Add(this.label6);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label6]));
			w11.X = 283;
			w11.Y = 180;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtPersonal = new global::Gtk.Entry();
			this.txtPersonal.CanFocus = true;
			this.txtPersonal.Name = "txtPersonal";
			this.txtPersonal.IsEditable = true;
			this.txtPersonal.InvisibleChar = '•';
			this.fixed1.Add(this.txtPersonal);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtPersonal]));
			w12.X = 406;
			w12.Y = 175;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Correo laboral");
			this.fixed1.Add(this.label7);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label7]));
			w13.X = 294;
			w13.Y = 227;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtLaboral = new global::Gtk.Entry();
			this.txtLaboral.CanFocus = true;
			this.txtLaboral.Name = "txtLaboral";
			this.txtLaboral.IsEditable = true;
			this.txtLaboral.InvisibleChar = '•';
			this.fixed1.Add(this.txtLaboral);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtLaboral]));
			w14.X = 407;
			w14.Y = 221;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvListaEmpleado = new global::Gtk.TreeView();
			this.tvListaEmpleado.WidthRequest = 500;
			this.tvListaEmpleado.HeightRequest = 150;
			this.tvListaEmpleado.CanFocus = true;
			this.tvListaEmpleado.Name = "tvListaEmpleado";
			this.GtkScrolledWindow.Add(this.tvListaEmpleado);
			this.fixed1.Add(this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
			w16.X = 59;
			w16.Y = 322;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnGuardar = new global::Gtk.Button();
			this.btnGuardar.CanFocus = true;
			this.btnGuardar.Name = "btnGuardar";
			this.btnGuardar.UseUnderline = true;
			this.btnGuardar.Label = global::Mono.Unix.Catalog.GetString("Guardar");
			this.fixed1.Add(this.btnGuardar);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnGuardar]));
			w17.X = 58;
			w17.Y = 273;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnEliminar = new global::Gtk.Button();
			this.btnEliminar.CanFocus = true;
			this.btnEliminar.Name = "btnEliminar";
			this.btnEliminar.UseUnderline = true;
			this.btnEliminar.Label = global::Mono.Unix.Catalog.GetString("Eliminar");
			this.fixed1.Add(this.btnEliminar);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnEliminar]));
			w18.X = 502;
			w18.Y = 275;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnModificar = new global::Gtk.Button();
			this.btnModificar.CanFocus = true;
			this.btnModificar.Name = "btnModificar";
			this.btnModificar.UseUnderline = true;
			this.btnModificar.Label = global::Mono.Unix.Catalog.GetString("Modificar");
			this.fixed1.Add(this.btnModificar);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnModificar]));
			w19.X = 272;
			w19.Y = 271;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnRegresar = new global::Gtk.Button();
			this.btnRegresar.CanFocus = true;
			this.btnRegresar.Name = "btnRegresar";
			this.btnRegresar.UseUnderline = true;
			this.btnRegresar.Label = global::Mono.Unix.Catalog.GetString("Regresar");
			this.fixed1.Add(this.btnRegresar);
			global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnRegresar]));
			w20.X = 22;
			w20.Y = 496;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtDireccion = new global::Gtk.Entry();
			this.txtDireccion.CanFocus = true;
			this.txtDireccion.Name = "txtDireccion";
			this.txtDireccion.IsEditable = true;
			this.txtDireccion.InvisibleChar = '•';
			this.fixed1.Add(this.txtDireccion);
			global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtDireccion]));
			w21.X = 405;
			w21.Y = 127;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtId = new global::Gtk.Entry();
			this.txtId.Sensitive = false;
			this.txtId.CanFocus = true;
			this.txtId.Name = "txtId";
			this.txtId.IsEditable = false;
			this.txtId.InvisibleChar = '•';
			this.fixed1.Add(this.txtId);
			global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtId]));
			w22.X = 403;
			w22.Y = 48;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("DIreccion");
			this.fixed1.Add(this.label8);
			global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label8]));
			w23.X = 329;
			w23.Y = 133;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("ID");
			this.fixed1.Add(this.label9);
			global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label9]));
			w24.X = 369;
			w24.Y = 55;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 626;
			this.DefaultHeight = 537;
			this.Show();
			this.tvListaEmpleado.CursorChanged += new global::System.EventHandler(this.OnTvListaEmpleadoCursorChanged);
			this.btnGuardar.Clicked += new global::System.EventHandler(this.OnBtnGuardarClicked);
			this.btnEliminar.Clicked += new global::System.EventHandler(this.OnBtnEliminarClicked);
			this.btnModificar.Clicked += new global::System.EventHandler(this.OnBtnModificarClicked);
			this.btnRegresar.Clicked += new global::System.EventHandler(this.OnBtnRegresarClicked);
		}
	}
}
