
// This file has been generated by the GUI designer. Do not modify.
namespace Sistema
{
	public partial class EntradaSalida
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label label1;

		private global::Gtk.Button btnEntrada;

		private global::Gtk.Button btnSalida;

		private global::Gtk.Label lblEmpleado;

		private global::Gtk.Button btnSalir;

		private global::Gtk.Calendar calendar1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Sistema.EntradaSalida
			this.Name = "Sistema.EntradaSalida";
			this.Title = global::Mono.Unix.Catalog.GetString("EntradaSalida");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Sistema.EntradaSalida.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Bienvenido usuario: ");
			this.fixed1.Add(this.label1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
			w1.X = 27;
			w1.Y = 44;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnEntrada = new global::Gtk.Button();
			this.btnEntrada.CanFocus = true;
			this.btnEntrada.Name = "btnEntrada";
			this.btnEntrada.UseUnderline = true;
			this.btnEntrada.Label = global::Mono.Unix.Catalog.GetString("Entrada");
			this.fixed1.Add(this.btnEntrada);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnEntrada]));
			w2.X = 78;
			w2.Y = 147;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnSalida = new global::Gtk.Button();
			this.btnSalida.CanFocus = true;
			this.btnSalida.Name = "btnSalida";
			this.btnSalida.UseUnderline = true;
			this.btnSalida.Label = global::Mono.Unix.Catalog.GetString("Salida");
			this.fixed1.Add(this.btnSalida);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnSalida]));
			w3.X = 221;
			w3.Y = 148;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblEmpleado = new global::Gtk.Label();
			this.lblEmpleado.Name = "lblEmpleado";
			this.fixed1.Add(this.lblEmpleado);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblEmpleado]));
			w4.X = 166;
			w4.Y = 44;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnSalir = new global::Gtk.Button();
			this.btnSalir.CanFocus = true;
			this.btnSalir.Name = "btnSalir";
			this.btnSalir.UseUnderline = true;
			this.btnSalir.Label = global::Mono.Unix.Catalog.GetString("Regresar");
			this.fixed1.Add(this.btnSalir);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnSalir]));
			w5.X = 27;
			w5.Y = 440;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.calendar1 = new global::Gtk.Calendar();
			this.calendar1.CanFocus = true;
			this.calendar1.Name = "calendar1";
			this.calendar1.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.fixed1.Add(this.calendar1);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.calendar1]));
			w6.X = 59;
			w6.Y = 199;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 381;
			this.DefaultHeight = 493;
			this.Show();
			this.btnEntrada.Clicked += new global::System.EventHandler(this.OnBtnEntradaClicked);
			this.btnSalida.Clicked += new global::System.EventHandler(this.OnBtnSalidaClicked);
			this.btnSalir.Clicked += new global::System.EventHandler(this.OnBtnSalirClicked);
		}
	}
}
