
// This file has been generated by the GUI designer. Do not modify.
namespace Sistema
{
	public partial class AdministrarCargo
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView tvAdministrarCargo;

		private global::Gtk.Label label3;

		private global::Gtk.Label label2;

		private global::Gtk.Label label1;

		private global::Gtk.Button btnGuardar;

		private global::Gtk.Button btnModificar;

		private global::Gtk.Button btnEliminar;

		private global::Gtk.Entry txtNombreCargo;

		private global::Gtk.Entry txtDescripcion;

		private global::Gtk.Entry txtIdDepartamento;

		private global::Gtk.Entry txtId;

		private global::Gtk.Label label4;

		private global::Gtk.Button btnRegresar;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Sistema.AdministrarCargo
			this.Name = "Sistema.AdministrarCargo";
			this.Title = global::Mono.Unix.Catalog.GetString("AdministrarCargo");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Sistema.AdministrarCargo.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvAdministrarCargo = new global::Gtk.TreeView();
			this.tvAdministrarCargo.WidthRequest = 500;
			this.tvAdministrarCargo.HeightRequest = 150;
			this.tvAdministrarCargo.CanFocus = true;
			this.tvAdministrarCargo.Name = "tvAdministrarCargo";
			this.GtkScrolledWindow.Add(this.tvAdministrarCargo);
			this.fixed1.Add(this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
			w2.X = 5;
			w2.Y = 287;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("IdDepartamento");
			this.fixed1.Add(this.label3);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
			w3.X = 39;
			w3.Y = 133;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Descripcion");
			this.fixed1.Add(this.label2);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
			w4.X = 39;
			w4.Y = 90;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre del cargo");
			this.fixed1.Add(this.label1);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
			w5.X = 38;
			w5.Y = 49;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnGuardar = new global::Gtk.Button();
			this.btnGuardar.CanFocus = true;
			this.btnGuardar.Name = "btnGuardar";
			this.btnGuardar.UseUnderline = true;
			this.btnGuardar.Label = global::Mono.Unix.Catalog.GetString("Guardar");
			this.fixed1.Add(this.btnGuardar);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnGuardar]));
			w6.X = 23;
			w6.Y = 229;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnModificar = new global::Gtk.Button();
			this.btnModificar.CanFocus = true;
			this.btnModificar.Name = "btnModificar";
			this.btnModificar.UseUnderline = true;
			this.btnModificar.Label = global::Mono.Unix.Catalog.GetString("Modificar");
			this.fixed1.Add(this.btnModificar);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnModificar]));
			w7.X = 216;
			w7.Y = 229;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnEliminar = new global::Gtk.Button();
			this.btnEliminar.CanFocus = true;
			this.btnEliminar.Name = "btnEliminar";
			this.btnEliminar.UseUnderline = true;
			this.btnEliminar.Label = global::Mono.Unix.Catalog.GetString("Eliminar");
			this.fixed1.Add(this.btnEliminar);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnEliminar]));
			w8.X = 412;
			w8.Y = 230;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtNombreCargo = new global::Gtk.Entry();
			this.txtNombreCargo.CanFocus = true;
			this.txtNombreCargo.Name = "txtNombreCargo";
			this.txtNombreCargo.IsEditable = true;
			this.txtNombreCargo.InvisibleChar = '•';
			this.fixed1.Add(this.txtNombreCargo);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtNombreCargo]));
			w9.X = 178;
			w9.Y = 39;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtDescripcion = new global::Gtk.Entry();
			this.txtDescripcion.CanFocus = true;
			this.txtDescripcion.Name = "txtDescripcion";
			this.txtDescripcion.IsEditable = true;
			this.txtDescripcion.InvisibleChar = '•';
			this.fixed1.Add(this.txtDescripcion);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtDescripcion]));
			w10.X = 177;
			w10.Y = 83;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtIdDepartamento = new global::Gtk.Entry();
			this.txtIdDepartamento.CanFocus = true;
			this.txtIdDepartamento.Name = "txtIdDepartamento";
			this.txtIdDepartamento.IsEditable = true;
			this.txtIdDepartamento.InvisibleChar = '•';
			this.fixed1.Add(this.txtIdDepartamento);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtIdDepartamento]));
			w11.X = 177;
			w11.Y = 126;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtId = new global::Gtk.Entry();
			this.txtId.Sensitive = false;
			this.txtId.CanFocus = true;
			this.txtId.Name = "txtId";
			this.txtId.IsEditable = false;
			this.txtId.InvisibleChar = '•';
			this.fixed1.Add(this.txtId);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtId]));
			w12.X = 177;
			w12.Y = 167;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("ID");
			this.fixed1.Add(this.label4);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label4]));
			w13.X = 73;
			w13.Y = 176;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnRegresar = new global::Gtk.Button();
			this.btnRegresar.CanFocus = true;
			this.btnRegresar.Name = "btnRegresar";
			this.btnRegresar.UseUnderline = true;
			this.btnRegresar.Label = global::Mono.Unix.Catalog.GetString("Regresar");
			this.fixed1.Add(this.btnRegresar);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnRegresar]));
			w14.X = 5;
			w14.Y = 464;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 520;
			this.DefaultHeight = 506;
			this.Show();
			this.tvAdministrarCargo.CursorChanged += new global::System.EventHandler(this.OnTvAdministrarCargoCursorChanged);
			this.btnGuardar.Clicked += new global::System.EventHandler(this.OnBtnGuardarClicked);
			this.btnModificar.Clicked += new global::System.EventHandler(this.OnBtnModificarClicked);
			this.btnEliminar.Clicked += new global::System.EventHandler(this.OnBtnEliminarClicked);
			this.btnRegresar.Clicked += new global::System.EventHandler(this.OnBtnRegresarClicked);
		}
	}
}
